### ISSUE TITLE
xxhash 0.7.2?

### ISSUE THREAD

**Issue by aldanor** [ifduyue/python-xxhash#33]
Hi! Would it be possible to update the C sources to v0.7.2 release a month ago? (https://github.com/Cyan4973/xxHash/releases/tag/v0.7.2)

**Comment by ifduyue** [comment]
Hello,

I'm waiting for [a new release of cibuildwheel](https://github.com/joerick/cibuildwheel/issues/170#issuecomment-549530535) so Python 3.8.0 wheels will be built and pushed to PyPI.

For python-xxhash, there aren't many differences between xxHash version 0.7.1 and 0.7.2, since python-xxhash provides only xxh32 and xxh64, no xxh3 yet. xxh3 is still experimental.

**Comment by ifduyue** [comment]
v1.4.3 is on TestPyPI https://test.pypi.org/project/xxhash/1.4.3/#files

**Comment by ifduyue** [comment]
v.1.4.3 released https://pypi.org/project/xxhash/1.4.3/#files
